import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';
import { v4 as uuid } from 'uuid';

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding database...');

  // Create demo users
  const adminPassword = await bcrypt.hash('admin123', 12);
  const recruiterPassword = await bcrypt.hash('recruiter123', 12);

  const admin = await prisma.user.upsert({
    where: { email: 'admin@qualirec.com' },
    update: {},
    create: {
      email: 'admin@qualirec.com',
      name: 'Admin User',
      passwordHash: adminPassword,
      role: 'ADMIN',
      preferences: { callViewMode: 'guided' },
    },
  });

  const recruiter = await prisma.user.upsert({
    where: { email: 'recruiter@qualirec.com' },
    update: {},
    create: {
      email: 'recruiter@qualirec.com',
      name: 'Sarah Johnson',
      passwordHash: recruiterPassword,
      role: 'RECRUITER',
      preferences: { callViewMode: 'guided' },
    },
  });

  const recruiter2 = await prisma.user.upsert({
    where: { email: 'recruiter2@qualirec.com' },
    update: {},
    create: {
      email: 'recruiter2@qualirec.com',
      name: 'Mike Chen',
      passwordHash: recruiterPassword,
      role: 'RECRUITER',
      preferences: { callViewMode: 'scroll' },
    },
  });

  console.log('Created users:', admin.email, recruiter.email, recruiter2.email);

  // Default Candidate Template 1: General Candidate Qualification
  const candidateTemplate1 = await prisma.template.upsert({
    where: { id: 'tpl-candidate-general' },
    update: {},
    create: {
      id: 'tpl-candidate-general',
      name: 'General Candidate Qualification',
      type: 'CANDIDATE',
      description: 'Standard qualification template for all candidate types. Covers essential screening points.',
      isDefault: true,
      createdById: admin.id,
      sections: [
        {
          id: uuid(),
          title: 'Current Situation',
          order: 0,
          questions: [
            {
              id: uuid(),
              text: 'What is your current role and employer?',
              hint: 'Get exact title and company name',
              responseType: 'FREE_TEXT',
              options: [],
              required: true,
              flagForCRM: true,
              crmFieldMapping: 'contact.current_role',
              order: 0,
            },
            {
              id: uuid(),
              text: 'How long have you been in this position?',
              hint: '',
              responseType: 'FREE_TEXT',
              options: [],
              required: false,
              flagForCRM: false,
              crmFieldMapping: '',
              order: 1,
            },
            {
              id: uuid(),
              text: 'What is your notice period or availability to start?',
              hint: 'Be specific - weeks or months',
              responseType: 'SINGLE_SELECT',
              options: ['Immediately', '2 weeks', '1 month', '2 months', '3+ months'],
              required: true,
              flagForCRM: true,
              crmFieldMapping: 'contact.notice_period',
              order: 2,
            },
            {
              id: uuid(),
              text: 'Do you have the right to work in the target country?',
              hint: 'Visa status — do they need sponsorship?',
              responseType: 'SINGLE_SELECT',
              options: ['Yes - Citizen/PR', 'Yes - Valid Work Visa', 'Needs Sponsorship', 'Not Sure'],
              required: true,
              flagForCRM: true,
              crmFieldMapping: 'contact.visa_status',
              order: 3,
            },
          ],
        },
        {
          id: uuid(),
          title: 'Compensation',
          order: 1,
          questions: [
            {
              id: uuid(),
              text: 'What is your current base salary?',
              hint: 'Get the number — annual, before tax',
              responseType: 'NUMERIC',
              options: [],
              required: true,
              flagForCRM: true,
              crmFieldMapping: 'contact.current_salary',
              order: 0,
            },
            {
              id: uuid(),
              text: 'Do you receive a bonus? If so, what percentage/amount?',
              hint: '',
              responseType: 'FREE_TEXT',
              options: [],
              required: false,
              flagForCRM: true,
              crmFieldMapping: 'contact.current_bonus',
              order: 1,
            },
            {
              id: uuid(),
              text: 'Do you have equity or stock options?',
              hint: 'Vesting schedule if applicable',
              responseType: 'YES_NO',
              options: [],
              required: false,
              flagForCRM: false,
              crmFieldMapping: '',
              order: 2,
            },
            {
              id: uuid(),
              text: 'What is your target compensation for your next role?',
              hint: 'Range is fine — capture min and ideal',
              responseType: 'FREE_TEXT',
              options: [],
              required: true,
              flagForCRM: true,
              crmFieldMapping: 'contact.target_salary',
              order: 3,
            },
          ],
        },
        {
          id: uuid(),
          title: 'Skills & Experience',
          order: 2,
          questions: [
            {
              id: uuid(),
              text: 'What are your key technical/professional skills?',
              hint: 'Focus on top 5-8 skills relevant to market',
              responseType: 'FREE_TEXT',
              options: [],
              required: true,
              flagForCRM: true,
              crmFieldMapping: 'contact.skills',
              order: 0,
            },
            {
              id: uuid(),
              text: 'How many years of experience do you have in your field?',
              hint: '',
              responseType: 'NUMERIC',
              options: [],
              required: true,
              flagForCRM: true,
              crmFieldMapping: 'contact.years_experience',
              order: 1,
            },
            {
              id: uuid(),
              text: 'What are your location preferences?',
              hint: 'Onsite, hybrid, remote? Willing to relocate?',
              responseType: 'MULTI_SELECT',
              options: ['Onsite', 'Hybrid', 'Fully Remote', 'Open to Relocation'],
              required: true,
              flagForCRM: true,
              crmFieldMapping: 'contact.location_preferences',
              order: 2,
            },
          ],
        },
        {
          id: uuid(),
          title: 'Motivation & Process',
          order: 3,
          questions: [
            {
              id: uuid(),
              text: 'What is motivating you to look for a new opportunity?',
              hint: 'Push vs pull factors — understand true motivation',
              responseType: 'FREE_TEXT',
              options: [],
              required: true,
              flagForCRM: false,
              crmFieldMapping: '',
              order: 0,
            },
            {
              id: uuid(),
              text: 'Are you currently interviewing elsewhere or have competing offers?',
              hint: 'Critical for urgency assessment',
              responseType: 'SINGLE_SELECT',
              options: ['No active processes', 'Early stages elsewhere', 'Advanced interviews', 'Have offer(s)'],
              required: true,
              flagForCRM: true,
              crmFieldMapping: 'contact.competing_offers',
              order: 1,
            },
            {
              id: uuid(),
              text: 'What is your availability for interviews?',
              hint: 'Specific days/times if possible',
              responseType: 'FREE_TEXT',
              options: [],
              required: false,
              flagForCRM: false,
              crmFieldMapping: '',
              order: 2,
            },
            {
              id: uuid(),
              text: 'Can you provide professional references?',
              hint: '',
              responseType: 'YES_NO',
              options: [],
              required: false,
              flagForCRM: false,
              crmFieldMapping: '',
              order: 3,
            },
          ],
        },
      ],
    },
  });

  // Default Candidate Template 2: Tech Candidate Deep Dive
  const candidateTemplate2 = await prisma.template.upsert({
    where: { id: 'tpl-candidate-tech' },
    update: {},
    create: {
      id: 'tpl-candidate-tech',
      name: 'Tech Candidate Deep Dive',
      type: 'CANDIDATE',
      description: 'Detailed qualification for software engineering and technical candidates. Includes technical depth questions.',
      isDefault: false,
      createdById: admin.id,
      sections: [
        {
          id: uuid(),
          title: 'Background & Current Role',
          order: 0,
          questions: [
            {
              id: uuid(),
              text: 'What is your current role, title, and company?',
              hint: 'Exact title matters for level matching',
              responseType: 'FREE_TEXT',
              options: [],
              required: true,
              flagForCRM: true,
              crmFieldMapping: 'contact.current_role',
              order: 0,
            },
            {
              id: uuid(),
              text: 'What is the size of your current team?',
              hint: 'Team size and structure helps assess seniority',
              responseType: 'FREE_TEXT',
              options: [],
              required: false,
              flagForCRM: false,
              crmFieldMapping: '',
              order: 1,
            },
            {
              id: uuid(),
              text: 'What is your notice period?',
              hint: '',
              responseType: 'SINGLE_SELECT',
              options: ['Immediately', '2 weeks', '1 month', '2 months', '3+ months'],
              required: true,
              flagForCRM: true,
              crmFieldMapping: 'contact.notice_period',
              order: 2,
            },
          ],
        },
        {
          id: uuid(),
          title: 'Technical Skills',
          order: 1,
          questions: [
            {
              id: uuid(),
              text: 'What are your primary programming languages?',
              hint: 'List top 3-5 with proficiency level',
              responseType: 'FREE_TEXT',
              options: [],
              required: true,
              flagForCRM: true,
              crmFieldMapping: 'contact.programming_languages',
              order: 0,
            },
            {
              id: uuid(),
              text: 'What frameworks and technologies do you work with daily?',
              hint: 'Frameworks, databases, cloud platforms, tools',
              responseType: 'FREE_TEXT',
              options: [],
              required: true,
              flagForCRM: true,
              crmFieldMapping: 'contact.tech_stack',
              order: 1,
            },
            {
              id: uuid(),
              text: 'What is your experience with cloud platforms?',
              hint: '',
              responseType: 'MULTI_SELECT',
              options: ['AWS', 'Azure', 'GCP', 'None'],
              required: false,
              flagForCRM: true,
              crmFieldMapping: 'contact.cloud_experience',
              order: 2,
            },
            {
              id: uuid(),
              text: 'Total years of professional software development experience?',
              hint: '',
              responseType: 'NUMERIC',
              options: [],
              required: true,
              flagForCRM: true,
              crmFieldMapping: 'contact.years_experience',
              order: 3,
            },
          ],
        },
        {
          id: uuid(),
          title: 'Compensation & Preferences',
          order: 2,
          questions: [
            {
              id: uuid(),
              text: 'Current total compensation (base + bonus + equity)?',
              hint: 'Break down base, bonus %, and equity value',
              responseType: 'FREE_TEXT',
              options: [],
              required: true,
              flagForCRM: true,
              crmFieldMapping: 'contact.current_compensation',
              order: 0,
            },
            {
              id: uuid(),
              text: 'Target compensation range for next role?',
              hint: '',
              responseType: 'FREE_TEXT',
              options: [],
              required: true,
              flagForCRM: true,
              crmFieldMapping: 'contact.target_salary',
              order: 1,
            },
            {
              id: uuid(),
              text: 'Work arrangement preference?',
              hint: '',
              responseType: 'SINGLE_SELECT',
              options: ['Fully Remote', 'Hybrid (2-3 days)', 'Onsite', 'Flexible'],
              required: true,
              flagForCRM: true,
              crmFieldMapping: 'contact.work_arrangement',
              order: 2,
            },
            {
              id: uuid(),
              text: 'Open to relocation?',
              hint: 'Where would they consider moving?',
              responseType: 'FREE_TEXT',
              options: [],
              required: false,
              flagForCRM: true,
              crmFieldMapping: 'contact.relocation',
              order: 3,
            },
            {
              id: uuid(),
              text: 'Visa / right-to-work status?',
              hint: '',
              responseType: 'SINGLE_SELECT',
              options: ['Citizen/PR', 'Valid Work Visa', 'Needs Sponsorship'],
              required: true,
              flagForCRM: true,
              crmFieldMapping: 'contact.visa_status',
              order: 4,
            },
          ],
        },
        {
          id: uuid(),
          title: 'Motivation & Pipeline',
          order: 3,
          questions: [
            {
              id: uuid(),
              text: 'Why are you considering a move right now?',
              hint: '',
              responseType: 'FREE_TEXT',
              options: [],
              required: true,
              flagForCRM: false,
              crmFieldMapping: '',
              order: 0,
            },
            {
              id: uuid(),
              text: 'What type of company/role excites you most?',
              hint: 'Startup vs enterprise, IC vs management, domain interests',
              responseType: 'FREE_TEXT',
              options: [],
              required: true,
              flagForCRM: false,
              crmFieldMapping: '',
              order: 1,
            },
            {
              id: uuid(),
              text: 'Active interview processes or offers?',
              hint: '',
              responseType: 'SINGLE_SELECT',
              options: ['None', 'Early stage', 'Final rounds', 'Have offer(s)'],
              required: true,
              flagForCRM: true,
              crmFieldMapping: 'contact.competing_offers',
              order: 2,
            },
            {
              id: uuid(),
              text: 'Interview availability in the next 2 weeks?',
              hint: '',
              responseType: 'FREE_TEXT',
              options: [],
              required: false,
              flagForCRM: false,
              crmFieldMapping: '',
              order: 3,
            },
          ],
        },
      ],
    },
  });

  // Default Client Template 1: General Client Intake
  const clientTemplate1 = await prisma.template.upsert({
    where: { id: 'tpl-client-general' },
    update: {},
    create: {
      id: 'tpl-client-general',
      name: 'General Client Intake',
      type: 'CLIENT',
      description: 'Standard intake template for qualifying new client roles and understanding hiring needs.',
      isDefault: true,
      createdById: admin.id,
      sections: [
        {
          id: uuid(),
          title: 'Company Overview',
          order: 0,
          questions: [
            {
              id: uuid(),
              text: 'Company name and brief overview?',
              hint: 'Industry, size, stage, notable info',
              responseType: 'FREE_TEXT',
              options: [],
              required: true,
              flagForCRM: true,
              crmFieldMapping: 'company.overview',
              order: 0,
            },
            {
              id: uuid(),
              text: 'Approximate headcount?',
              hint: '',
              responseType: 'NUMERIC',
              options: [],
              required: false,
              flagForCRM: true,
              crmFieldMapping: 'company.headcount',
              order: 1,
            },
          ],
        },
        {
          id: uuid(),
          title: 'Role Details',
          order: 1,
          questions: [
            {
              id: uuid(),
              text: 'What is the role title and level?',
              hint: 'Get exact title they want to use in job spec',
              responseType: 'FREE_TEXT',
              options: [],
              required: true,
              flagForCRM: true,
              crmFieldMapping: 'role.title',
              order: 0,
            },
            {
              id: uuid(),
              text: 'Who does this role report to?',
              hint: 'Title and name of hiring manager',
              responseType: 'FREE_TEXT',
              options: [],
              required: true,
              flagForCRM: true,
              crmFieldMapping: 'role.reporting_line',
              order: 1,
            },
            {
              id: uuid(),
              text: 'What are the key responsibilities?',
              hint: 'Top 3-5 priorities in the first 6 months',
              responseType: 'FREE_TEXT',
              options: [],
              required: true,
              flagForCRM: false,
              crmFieldMapping: '',
              order: 2,
            },
            {
              id: uuid(),
              text: 'Must-have skills/experience?',
              hint: 'Absolute dealbreakers — what they cannot flex on',
              responseType: 'FREE_TEXT',
              options: [],
              required: true,
              flagForCRM: true,
              crmFieldMapping: 'role.must_have_skills',
              order: 3,
            },
            {
              id: uuid(),
              text: 'Nice-to-have skills/experience?',
              hint: 'Would strengthen a candidate but not required',
              responseType: 'FREE_TEXT',
              options: [],
              required: false,
              flagForCRM: true,
              crmFieldMapping: 'role.nice_to_have_skills',
              order: 4,
            },
          ],
        },
        {
          id: uuid(),
          title: 'Compensation & Location',
          order: 2,
          questions: [
            {
              id: uuid(),
              text: 'What is the compensation budget (base salary range)?',
              hint: 'Get firm numbers — min and max approved',
              responseType: 'FREE_TEXT',
              options: [],
              required: true,
              flagForCRM: true,
              crmFieldMapping: 'role.salary_range',
              order: 0,
            },
            {
              id: uuid(),
              text: 'Total package details (bonus, equity, benefits)?',
              hint: '',
              responseType: 'FREE_TEXT',
              options: [],
              required: false,
              flagForCRM: true,
              crmFieldMapping: 'role.total_package',
              order: 1,
            },
            {
              id: uuid(),
              text: 'Location / remote policy?',
              hint: '',
              responseType: 'SINGLE_SELECT',
              options: ['Fully Onsite', 'Hybrid', 'Fully Remote', 'Flexible'],
              required: true,
              flagForCRM: true,
              crmFieldMapping: 'role.location_policy',
              order: 2,
            },
            {
              id: uuid(),
              text: 'Office location(s)?',
              hint: '',
              responseType: 'FREE_TEXT',
              options: [],
              required: false,
              flagForCRM: true,
              crmFieldMapping: 'role.office_location',
              order: 3,
            },
          ],
        },
        {
          id: uuid(),
          title: 'Process & Urgency',
          order: 3,
          questions: [
            {
              id: uuid(),
              text: 'What is the interview process and timeline?',
              hint: 'Number of stages, who is involved, how long',
              responseType: 'FREE_TEXT',
              options: [],
              required: true,
              flagForCRM: true,
              crmFieldMapping: 'role.interview_process',
              order: 0,
            },
            {
              id: uuid(),
              text: 'How urgent is this hire?',
              hint: '',
              responseType: 'SINGLE_SELECT',
              options: ['Critical - ASAP', 'High - Within 1 month', 'Medium - Within 3 months', 'Low - Pipeline building'],
              required: true,
              flagForCRM: true,
              crmFieldMapping: 'role.urgency',
              order: 1,
            },
            {
              id: uuid(),
              text: 'What is the reason for this hire?',
              hint: 'New headcount, backfill, growth, restructure',
              responseType: 'SINGLE_SELECT',
              options: ['New Headcount', 'Backfill', 'Team Growth', 'Restructure'],
              required: true,
              flagForCRM: true,
              crmFieldMapping: 'role.hire_reason',
              order: 2,
            },
            {
              id: uuid(),
              text: 'Who makes the final hiring decision?',
              hint: 'Decision maker name and title',
              responseType: 'FREE_TEXT',
              options: [],
              required: true,
              flagForCRM: true,
              crmFieldMapping: 'role.decision_maker',
              order: 3,
            },
            {
              id: uuid(),
              text: 'Have you tried to fill this role before?',
              hint: 'What happened? Why did it fail? Any agency involvement?',
              responseType: 'FREE_TEXT',
              options: [],
              required: false,
              flagForCRM: false,
              crmFieldMapping: '',
              order: 4,
            },
          ],
        },
      ],
    },
  });

  // Default Client Template 2: Executive/Leadership Intake
  const clientTemplate2 = await prisma.template.upsert({
    where: { id: 'tpl-client-executive' },
    update: {},
    create: {
      id: 'tpl-client-executive',
      name: 'Executive/Leadership Intake',
      type: 'CLIENT',
      description: 'Detailed intake for executive and leadership hiring. Covers strategic context and board-level considerations.',
      isDefault: false,
      createdById: admin.id,
      sections: [
        {
          id: uuid(),
          title: 'Organization Context',
          order: 0,
          questions: [
            {
              id: uuid(),
              text: 'Company overview, stage, and strategic direction?',
              hint: 'Revenue range, funding stage, growth trajectory',
              responseType: 'FREE_TEXT',
              options: [],
              required: true,
              flagForCRM: true,
              crmFieldMapping: 'company.overview',
              order: 0,
            },
            {
              id: uuid(),
              text: 'Current leadership team structure?',
              hint: 'Who is on the exec team today?',
              responseType: 'FREE_TEXT',
              options: [],
              required: true,
              flagForCRM: false,
              crmFieldMapping: '',
              order: 1,
            },
            {
              id: uuid(),
              text: 'Board composition and involvement level?',
              hint: '',
              responseType: 'FREE_TEXT',
              options: [],
              required: false,
              flagForCRM: false,
              crmFieldMapping: '',
              order: 2,
            },
          ],
        },
        {
          id: uuid(),
          title: 'Role Specification',
          order: 1,
          questions: [
            {
              id: uuid(),
              text: 'Exact title and reporting line?',
              hint: '',
              responseType: 'FREE_TEXT',
              options: [],
              required: true,
              flagForCRM: true,
              crmFieldMapping: 'role.title',
              order: 0,
            },
            {
              id: uuid(),
              text: 'What is the strategic mandate for this role?',
              hint: 'What must this leader achieve in 12-18 months?',
              responseType: 'FREE_TEXT',
              options: [],
              required: true,
              flagForCRM: false,
              crmFieldMapping: '',
              order: 1,
            },
            {
              id: uuid(),
              text: 'Team size this role will manage?',
              hint: 'Direct reports and total org',
              responseType: 'FREE_TEXT',
              options: [],
              required: true,
              flagForCRM: true,
              crmFieldMapping: 'role.team_size',
              order: 2,
            },
            {
              id: uuid(),
              text: 'P&L or budget responsibility?',
              hint: '',
              responseType: 'FREE_TEXT',
              options: [],
              required: false,
              flagForCRM: true,
              crmFieldMapping: 'role.budget_responsibility',
              order: 3,
            },
          ],
        },
        {
          id: uuid(),
          title: 'Candidate Profile',
          order: 2,
          questions: [
            {
              id: uuid(),
              text: 'Must-have experience and background?',
              hint: 'Industry, company type, scale, functional expertise',
              responseType: 'FREE_TEXT',
              options: [],
              required: true,
              flagForCRM: true,
              crmFieldMapping: 'role.must_have_skills',
              order: 0,
            },
            {
              id: uuid(),
              text: 'Leadership style and culture fit considerations?',
              hint: '',
              responseType: 'FREE_TEXT',
              options: [],
              required: true,
              flagForCRM: false,
              crmFieldMapping: '',
              order: 1,
            },
            {
              id: uuid(),
              text: 'Compensation range (base + total package)?',
              hint: 'Get board-approved range',
              responseType: 'FREE_TEXT',
              options: [],
              required: true,
              flagForCRM: true,
              crmFieldMapping: 'role.salary_range',
              order: 2,
            },
            {
              id: uuid(),
              text: 'Equity/options component?',
              hint: '',
              responseType: 'FREE_TEXT',
              options: [],
              required: false,
              flagForCRM: true,
              crmFieldMapping: 'role.equity',
              order: 3,
            },
          ],
        },
        {
          id: uuid(),
          title: 'Process',
          order: 3,
          questions: [
            {
              id: uuid(),
              text: 'Interview process — who is involved at each stage?',
              hint: '',
              responseType: 'FREE_TEXT',
              options: [],
              required: true,
              flagForCRM: true,
              crmFieldMapping: 'role.interview_process',
              order: 0,
            },
            {
              id: uuid(),
              text: 'Timeline — when do they need someone in seat?',
              hint: '',
              responseType: 'FREE_TEXT',
              options: [],
              required: true,
              flagForCRM: true,
              crmFieldMapping: 'role.timeline',
              order: 1,
            },
            {
              id: uuid(),
              text: 'Confidentiality level?',
              hint: 'Is this a replacement? Is the search confidential?',
              responseType: 'SINGLE_SELECT',
              options: ['Public', 'Internal only', 'Confidential replacement', 'Highly confidential'],
              required: true,
              flagForCRM: false,
              crmFieldMapping: '',
              order: 2,
            },
            {
              id: uuid(),
              text: 'Exclusivity expectations?',
              hint: 'Retained vs contingent? Other agencies involved?',
              responseType: 'FREE_TEXT',
              options: [],
              required: true,
              flagForCRM: false,
              crmFieldMapping: '',
              order: 3,
            },
          ],
        },
      ],
    },
  });

  // Create default integration configs
  await prisma.integrationConfig.upsert({
    where: {
      userId_adapterType_adapterName: {
        userId: admin.id,
        adapterType: 'CRM',
        adapterName: 'mock',
      },
    },
    update: {},
    create: {
      userId: admin.id,
      adapterType: 'CRM',
      adapterName: 'mock',
      isActive: true,
      credentials: {},
    },
  });

  // Create some sample CRM contacts for the mock adapter
  await prisma.crmContact.upsert({
    where: { id: 'crm-contact-1' },
    update: {},
    create: {
      id: 'crm-contact-1',
      firstName: 'John',
      lastName: 'Smith',
      email: 'john.smith@example.com',
      phone: '+1-555-0101',
      company: 'TechCorp',
      title: 'Senior Software Engineer',
      source: 'qualirec',
      fields: { skills: 'React, Node.js, Python', yearsExperience: 8 },
    },
  });

  await prisma.crmContact.upsert({
    where: { id: 'crm-contact-2' },
    update: {},
    create: {
      id: 'crm-contact-2',
      firstName: 'Emily',
      lastName: 'Davis',
      email: 'emily.davis@innovate.io',
      phone: '+1-555-0102',
      company: 'Innovate.io',
      title: 'VP of Engineering',
      source: 'qualirec',
      fields: { headcount: 250, industry: 'SaaS' },
    },
  });

  await prisma.crmContact.upsert({
    where: { id: 'crm-contact-3' },
    update: {},
    create: {
      id: 'crm-contact-3',
      firstName: 'Alex',
      lastName: 'Johnson',
      email: 'alex.j@dataflow.com',
      phone: '+1-555-0103',
      company: 'DataFlow Inc',
      title: 'Data Scientist',
      source: 'qualirec',
      fields: { skills: 'Python, ML, TensorFlow', yearsExperience: 5 },
    },
  });

  console.log('Created templates:', candidateTemplate1.name, candidateTemplate2.name, clientTemplate1.name, clientTemplate2.name);
  console.log('Seed completed successfully!');
}

main()
  .catch((e) => {
    console.error('Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
